# Generated by Django 2.2.3 on 2019-08-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20190731_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='numero',
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
